ProjetTutoreFabMSTIC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import(
    MaterialDetailView,
    LoanSummaryView,
    loan_form,
)

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
                  # path('admin/', admin.site.urls),
                  path("", views.homepage, name="homepage"),
                  path("register/", views.register, name="register"),
                  path("logout/", views.logout_request, name="logout"),
                  path("login/", views.login_request, name="login"),
                  path("loan-summary/", LoanSummaryView.as_view(), name="loan-summary"),
                  path("material/", views.material_form, name="material"),
                  path("type/", views.type_form, name="type"),
                  path("loaner/", views.loaner_form, name="loaner"),
                  path("loan/", loan_form.as_view(), name="loan"),

                  path("material/<slug>/", MaterialDetailView.as_view(), name='material'),
                  path("add-to-loan/<slug>", views.add_to_loan, name='add-to-loan'),
                  path("remove-from-loan/<slug>", views.remove_from_loan, name='remove-from-loan'),
                  path("remove-material-from-loan/<slug>", views.remove_single_item_from_loan, name='remove-material-from-loan'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from .choices import *
from django.utils import timezone
from django.shortcuts import reverse
from django.conf import settings

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Loaner(models.Model):
    last_name = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    establishment = models.CharField(max_length=250)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.last_name + " " + self.first_name


class Type(models.Model):
    material_type = models.CharField(max_length=250, choices=TYPE_CHOICES, default=TYPE_GENERIC)
    name_type = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    creation_date_type = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0}".format(self.name_type)


class Material(models.Model):
    name = models.CharField(max_length=250)
    barcode = models.IntegerField(blank=False, primary_key=True)
    creation_date_mat = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    material_picture = models.ImageField(blank=True, upload_to='media/', default='None/no-img.jpg', null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + " (barcode:  " + str(self.barcode) + ")"

    def get_absolute_url(self):
        return reverse("main:material", kwargs={
            'slug': self.slug
        })

    def get_add_to_loan_url(self):
        return reverse("main:add-to-loan", kwargs={
            'slug': self.slug
        })

    def get_remove_from_loan_url(self):
        return reverse("main:remove-from-loan", kwargs={
            'slug': self.slug
        })


class LoanMaterial(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)

    quantity = models.IntegerField(blank=False, default=1)
    creation_date_loan_mat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.quantity) + " of " + self.material.name


class Loan(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    creation_date_loan = models.DateTimeField(default=timezone.now)
    expected_return_date = models.DateField(blank=True, null=True)
    return_date = models.DateField(null=True)

    loaner = models.ForeignKey(Loaner, on_delete=models.CASCADE, blank=False, null=True)
    materials = models.ManyToManyField(LoanMaterial)

    def __str__(self):
        return "{0}".format(self.pk)

main/forms.py
from random import choices
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Material, Type, Loan, LoanMaterial, Loaner
from django import forms
from .choices import *
from django.db import models
from django.forms import formset_factory


# from django.forms import ModelForm

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ('loaner', 'expected_return_date')


class LoanerForm(forms.ModelForm):
    class Meta:
        model = Loaner
        exclude = ['creation_date']


class TypeForm(forms.ModelForm):
    material_type = models.CharField(choices=TYPE_CHOICES, default='generic')

    class Meta:
        model = Type
        fields = '__all__'


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        # fields = '__all__'
        exclude = ['creation_date_mat']


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    establishment = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "establishment", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.establishment = self.cleaned_data['establishment']
        if commit:
            user.save()
        return user

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from .models import Type, Material, Loan, LoanMaterial, UserProfile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from .forms import NewUserForm, TypeForm, MaterialForm, LoanerForm, LoanForm
from .models import Material, Type
from django.contrib import messages
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def homepage(request):
    materials = Material.objects.all()

    search_term = ""

    if 'search' in request.GET:
        search_term = request.GET['search']
        materials = (materials.filter(name__icontains=search_term) | materials.filter(barcode__icontains=search_term))

        if search_term == "":
            search_term = "No match."

    paginator = Paginator(materials, 8)

    page = request.GET.get('page')

    materials = paginator.get_page(page)

    return render(request=request,
                  template_name="main/home.html",
                  context={"materials": materials, "search_term": search_term})


class MaterialDetailView(DetailView):
    model = Material
    template_name = "main/material.html"


def register(request):
    # automatically, it's a GET request

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            # things are filled out like theyre supposed to
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created:{username}")
            login(request, user)
            messages.info(request, f"Logged in as  {username}")
            return redirect("main:homepage")
        else:
            for message in form.error_messages:
                # print(form.error_messages[message])
                messages.error(request, f"{message} : {form.error_messages[message]}")
    form = NewUserForm
    return render(request,
                  "main/register.html",
                  context={"form": form}
                  )


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:homepage")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Logged in as  {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")

    form = AuthenticationForm()
    return render(request,
                  "main/login.html",
                  {"form": form}
                  )


def material_form(request):
    sauvegarde = False
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        if form.is_valid():
            from django.core.exceptions import ObjectDoesNotExist
            try:
                material_unique = form.cleaned_data.get('type')
                Material.objects.get(type=material_unique)
                messages.error(request, f"Existing unique type.")
            except ObjectDoesNotExist:
                form.save()
                form = MaterialForm()
                messages.success(request, f"New Material created")
                return redirect("main:homepage")
                sauvegarde = True
    else:
        form = MaterialForm()
    return render(request, 'main/materialForm.html', {'form': form, 'sauvegarde': sauvegarde})


def type_form(request):
    sauvegarde = False
    if request.method == 'POST':
        form = TypeForm(request.POST)
        form.save()
        form = TypeForm()
        messages.success(request, f"New Type created")
        return redirect("main:homepage")
        sauvegarde = True
    else:
        form = TypeForm()
    return render(request, 'main/typeForm.html/', {'form': form, 'sauvegarde': sauvegarde})


def loaner_form(request):
    sauvegarde = False
    if request.method == 'POST':
        form = LoanerForm(request.POST)
        form.save()
        form = LoanerForm()
        messages.success(request, f"New Loaner created")
        return redirect("main:homepage")
        sauvegarde = True
    else:
        form = LoanerForm()
    return render(request, 'main/loanerForm.html/', {'form': form, 'sauvegarde': sauvegarde})


@login_required
def add_to_loan(request, slug):
    material = get_object_or_404(Material, slug=slug)
    loan_material, created = LoanMaterial.objects.get_or_create(material=material, user=request.user, ordered=False)
    material_query = Loan.objects.filter(user=request.user, ordered=False)
    if material_query.exists():
        loan = material_query[0]
        # check if the order item is in the order
        if loan.materials.filter(material__slug=material.slug).exists():
            loan_material.quantity += 1
            loan_material.save()
            messages.info(request, loan_material)
            return redirect("main:material", slug=slug)
        else:
            loan.materials.add(loan_material)
            messages.info(request, loan_material)
            return redirect("main:material", slug=slug)

    else:
        loan_date = timezone.now()
        loan = Loan.objects.create(user=request.user, creation_date_loan=loan_date)
        loan.materials.add(loan_material)
        messages.info(request, "This item was added to your cart.")
        return redirect("main:material", slug=slug)


@login_required
def remove_from_loan(request, slug):
    material = get_object_or_404(Material, slug=slug)
    material_query = Loan.objects.filter(user=request.user, ordered=False)

    if material_query.exists():
        loan = material_query[0]
        # check if the order item is in the order
        if loan.materials.filter(material__slug=material.slug).exists():
            loan_material = LoanMaterial.objects.filter(material=material, user=request.user, ordered=False)[0]
            loan.materials.remove(loan_material)
            loan_material.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("main:loan-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("main:material", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("main:material", slug=slug)


@login_required
def remove_single_item_from_loan(request, slug):
    material = get_object_or_404(Material, slug=slug)
    material_query = Loan.objects.filter(user=request.user, ordered=False)
    if material_query.exists():
        loan = material_query[0]
        # check if the order item is in the order
        if loan.materials.filter(material__slug=material.slug).exists():
            loan_material = LoanMaterial.objects.filter(
                material=material,
                user=request.user,
                ordered=False)[0]
            if loan_material.quantity > 1:
                loan_material.quantity -= 1
                loan_material.save()
            else:
                loan.materials.remove(loan_material)
            messages.info(request, "This item quantity was updated.")
            return redirect("main:loan-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("main:material", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("main:material", slug=slug)


class LoanSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            loan = Loan.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': loan
            }
            return render(self.request, 'main/loan_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


class loan_form(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            form = LoanForm()
            context = {
                'formLoan': form,
            }
            return render(self.request, 'main/loanForm.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

    def post(self, *args, **kwargs):
        form = LoanForm(self.request.POST or None)
        loan = Loan.objects.get(user=self.request.user, ordered=False)
        try:
            if form.is_valid():
                expected_return = form.cleaned_data.get('expected_return_date')

                loan.ordered = True
                loan.save()

                loan.expected_return_date = expected_return
                loan.save()

                loan.loaner = form.cleaned_data.get('loaner')
                loan.save()

                loan.user = self.request.user
                loan.save()

                loan_materials = loan.materials.all()
                loan_materials.update(ordered=True)
                for material in loan_materials:
                    material.save()

                messages.success(self.request, f" Loan saved successfully")

main/templates/main/header.html
<head>

{% load static %}
<!-- start -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous">
    <link rel="stylesheet"
      href="{% static 'css/pagination.css' %}">
    <!-- end -->
    <!-- Prism CSS -->
<!--    <link href="{% static 'static/main/css/materialize.min.css' %}" rel="stylesheet">-->
<!--    <link href="{% static 'static/main/js/materialize.min.js' %}" rel="stylesheet">-->
<!--    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">-->
<!--     Compiled and minified CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<!--     Compiled and minified JavaScript-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>

    {% include "main/includes/navbaritems.html" %}

    {% include "main/includes/messaging.html" %}

  <div class = "container">
      <br>
      {% block content %}
      {% endblock %}
  </div>
</body>

<!-- Prism JS -->
<script src="{% static 'tinymce/js/prism.js' %}"></script>

main/templates/main/header_secondary.html
<head>

{% load static %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous">
    <link rel="stylesheet"
      href="{% static 'css/pagination.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<!--     Compiled and minified JavaScript-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>

    {% include "main/includes/navbar-secondary.html" %}

    {% include "main/includes/messaging.html" %}

  <div class = "container">
      <br>
      {% block content %}
      {% endblock %}
  </div>
</body>

<!-- Prism JS -->
<script src="{% static 'tinymce/js/prism.js' %}"></script>

main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}

{% if materials.paginator.num_pages > 1 %}
    <!-- start -->
    {% include "main/includes/pagination.html" %}
    <!-- end -->
{% endif %}



<div class="row">
    {% if not materials %}
        <p>No Match Found.</p>
    {% endif %}
  {% for material in materials %}
      <div class="col s12 m6">
        <div class="card blue-grey lighten-5 hoverable">
          <div class="card-content black-text">
            <span class="card-title">{{material.name}}</span>
             <p class="card-title" style="font-size:70%">Barcode: {{material.barcode}}</p>
             <p style="font-size:70%"> Created at: {{material.creation_date_mat}}</p>
             <p style="font-size:70%">{{material.type|safe}}</p>
             <p>{{  material.material_picture }} Foto</p>
             <img src="images/{{material.material_picture}}" width="240">
<!--             <p style="font-size:80%"><b>Description:</b> {{material.description|safe}}</p>-->
           </div>
          <div class="card-action">
            <a href="{{ material.get_absolute_url }}">View Material</a>
          </div>
        </div>
      </div>
  {% endfor %}
</div>

{% if materials.paginator.num_pages > 1 %}
    <!-- start -->
    {% include "main/includes/pagination.html" %}
    <!-- end -->
{% endif %}

{% endblock %}

main/templates/main/loanForm.html
{% include "main/includes/navbar-secondary.html" %}

{% include "main/includes/messaging.html" %}

{% block content %}
<div class = "container">
    {% if user.is_authenticated %}
        <br>
        <h3> <span class="badge badge-secondary">Add Loaner</span></h3>
        <br>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ formLoan.as_p }}
            <br>
            <button class="btn btn-dark" type = "submit">Save Loan</button>
        </form>
        If you want to create a new Loaner, go to <strong><a href = 'loaner/'> LOANER</a></strong>.
    {% else %}
        <p>You don't have permission to access this page. Return Home.</p>
    {% endif %}
</div>
{% endblock %}

main/templates/main/loan_summary.html
{% include "main/header_secondary.html" %}

{% block content %}
  <main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Loan Summary</h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Material Name</th>
                    <th scope="col">Barcode</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Commands</th>
                </tr>
                </thead>
                <tbody>
                {% for loan_material in object.materials.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ loan_material.material.name }}</td>
                    <td>{{ loan_material.material.barcode }}</td>
                    <td>
                        <a href="{% url 'main:remove-material-from-loan' loan_material.material.slug  %}"><i class="material-icons">remove_circle</i></a>
                        {{ loan_material.quantity }}
                        <a href="{% url 'main:add-to-loan' loan_material.material.slug  %}"><i class="material-icons right">add_circle</i></a></td>
                    <td>
                        <a href="{% url 'main:remove-from-loan' loan_material.material.slug  %}"><i class="material-icons right">delete</i></a>
                    </td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan='5'>Your cart is empty</td>
                </tr>
                <tr>
                    <td colspan="5">
                        <a class="btn btn-warning float-right" href="/">Continue Adding</a>
                    </td>
                </tr>
                {% endfor %}
                     <tr>
                    <td colspan="5">
                        <a class="btn btn-primary float-right" href="../loan">Proceed to Checkout</a>
                        <a class="btn btn-warning float-right" href="/">Continue Adding</a>
                    </td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>

  </main>
{% endblock %}

main/templates/main/loanerForm.html
{% include "main/includes/navbar-secondary.html" %}

{% include "main/includes/messaging.html" %}
{% block content %}
    <div class = "container">
            {% if user.is_authenticated %}
                <br>
                <h3> <span class="badge badge-secondary">Add a Loaner</span></h3>
                <br>
                <form method = "POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button class="btn btn-dark" type = "submit">Add Loaner</button>
                </form>
                If you already have an account, <strong><a href = 'login/'>login</a></strong>.
        {% else %}
            <p>You don't have permission to access this page. Return Home.</p>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/login.html
{% extends "main/header.html" %}
{% block content %}
    <form method = "POST">
        {% csrf_token %}
        {{ form.as_p  }}
        <br>
        <button class = "btn" type = "submit">Login</button>
    </form>
If you already have an account, <strong><a href = '/register'>register</a></strong> instead.
{% endblock %}

main/templates/main/material.html
{% extends "main/header.html" %}
{% block content %}
<div class = "container">
    <div class="card-content black-text">
        <span class="card-title" style="font-size:270%">{{ object.name }}</span>
        <p class="card-title" style="font-size:120%">Barcode: {{ object.barcode }}</p>
        <p style="font-size:120%">{{ object.type }}</p>
        <p> Description: {{ object.type.description }}</p>
        <img src="../../images/{{object.material_picture}}" width="700">
        {% if user.is_authenticated %}
            <br><br><a href="{{ object.get_add_to_loan_url }}" class = "btn dropdown-button green darken-4">Add to Loan</a>
            <a href="{{ object.get_remove_from_loan_url }}" class = "btn dropdown-button red darken-4">Remove From Cart</a>
        {% endif %}
    </div>
</div>
{% endblock %}

main/templates/main/materialForm.html
{% include "main/includes/navbar-secondary.html" %}

{% include "main/includes/messaging.html" %}

{% block content %}
<div class = "container">
    {% if user.is_authenticated %}
        <br>
        <h3> <span class="badge badge-secondary">Add a Material</span></h3>
        <br>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button class="btn btn-dark" type = "submit">Add Material</button>
        </form>
        If you already have an account, <strong><a href = 'login/'>login</a></strong>.
    {% else %}
        <p>You don't have permission to access this page. Return Home.</p>
    {% endif %}
</div>
{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}
{% block content %}
    <form method = "POST">
        {% csrf_token %}
        {{ form.as_p  }}
        <br>
        <button class = "btn" type = "submit">Register A Staff Member</button>
    </form>
If you already have an account, <strong><a href = '/login'>login</a></strong> instead.
{% endblock %}

main/templates/main/typeForm.html
{% include "main/includes/navbar-secondary.html" %}
{% block content %}
 <div class = "container">
    {% if user.is_authenticated %}

        <br>
        <h3> <span class="badge badge-secondary">Add a Type</span></h3>
        <br>
        <form method = "POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button class="btn btn-dark" type = "submit">Add Type</button>
        </form>
        If you already have an account, <strong><a href = 'login/'>login</a></strong>.
         </div>
    {% else %}
        <p>You don't have permission to access this page. Return Home.</p>
    {% endif %}
</div>
{% endblock %}